### ISSUE TITLE
support recur/rec (y-combinators)

### ISSUE THREAD

**Issue by ice1000** [bC-Programming-Language-StandardCouncil/bC-Document#12]
添加对rec（或者叫recur）的支持。它只能在lambda内部被使用，代表这个lambda自身。

比如，我们需要写一个匿名的递归函数。举的例子是阶乘。

```rust
execFun(10) { n: i32 ->
  if (n == 0) return 1;
  else return n * recur(n - 1);
}
```

**Comment by Seng-Jik** [comment]
我同意，没问题

**Comment by ice1000** [comment]
好，那我加个专门的AST结构代表这个东西。


Edit: 不需要了，做成变量了

**Comment by ice1000** [comment]
那么这个东西应该是一个保留字。目前编译器后端是通过在新建lambda时隐式定义一个变量指向自身的方法实现的，因此其他变量就不能叫这个名字。

**Comment by Seng-Jik** [comment]
没问题，不过我们可以推广到所有函数里都可以用recur表示自己吗

**Comment by ice1000** [comment]
根据我的推导方法，

```cm
i32{ i: i32 -> string{ s: string -> recur(233) } }
```

都能通过编译的（就是recur成了重载的变量）

**Comment by ice1000** [comment]
上面那个特性还没测试过。目前的要求就是，如果用到了`recur`，那么这个lambda必须手动声明类型。

我花了很长时间确保这个特性不会影响以前的推导。现在编译器的代码变得蛋疼了起来。。

**Comment by thautwarm** [comment]
### 一个问题   
嵌套的lambda如何处理`recur`?  
```rust
execFun(10) { n: i32 ->
   
   { n: i32 ->
     if (n == 0) return 1;
     else return n * recur(n - 1); //这个recur是指哪个？
   }

  if (n == 0) return 1;
  else return n * recur(n - 1);
}
```
我想的是能不能这样处理：
- 默认recur指向当前的lambda。
- 可用`label`来手动标记。
```rust
execFun(10)  {
    lambda1:   
    n: i32 ->
   {
     lambda2:
     n: i32 ->
      
     if (n == 0) return 1;
     else return n * recur(n - 1); //该recur <=> lambda2.recur
   }

  if (n == 0) return 1;
  else return n * recur(n - 1);
}
```

**Comment by ice1000** [comment]
@thautwarm 愚蠢的人类

你注意看我[这条回复](https://github.com/Cm-lang/Cm-Document/issues/12#issuecomment-326793459)

**Comment by ice1000** [comment]
recur被处理成变量了，然后根据Cm处理重载函数的特点，按理说是可以根据参数的类型找到外面的lambda的。要是覆盖了那就鸡寄。

**Comment by ice1000** [comment]
加label的话，语法上是有歧义的。

`lamdba1: a: i32`

这样的东西，那也可以是`lambda1`是参数名，`a`是类型，然后遇到`i32`，就Unexpected Token

**Comment by ice1000** [comment]
Kotlin的做法是，用艾特这个符号表示label。

```kotlin
loop1@ {
  return@loop1
}
```

但是这个不好做。可能会涉及比较麻烦的重构。

**Comment by ice1000** [comment]
你不回我。我关了 :trollface:

**Comment by ice1000** [comment]
做出来了，测试成功。

```rust
let recurFunc = i8 { a: i8 -> i8 { recur(a) }() }
var gg: i8
gg = recurFunc(233)
```

这样的表达式，对应的AST长这样：

```yaml
statement list:
  variable declaration [recurFunc]:
    type:
      lambda type [(i8)->i8]
    initialize expression:
      lambda:
        type:
          lambda type [(i8)->i8]
        parameters:
          variable declaration [a]:
            type:
              primary type [i8]
            initialize expression:
              null expression
        body:
          statement list:
            return statement:
              function call expression:
                receiver:
                  lambda:
                    type:
                      lambda type [()->i8]
                    parameters:
                    body:
                      statement list:
                        return statement:
                          function call expression:
                            receiver:
                              variable expression [recur]:
                                type:
                                  lambda type [(i8)->i8]
                            parameters:
                              variable expression [a]:
                                type:
                                  primary type [i8]
                            type:
                              primary type [i8]
                parameters:
                type:
                  primary type [i8]
  variable declaration [gg]:
    type:
      primary type [i8]
    initialize expression:
      null expression
  assignment statemnt:
    lhs:
      variable expression [gg]:
        type:
          primary type [i8]
    rhs:
      function call expression:
        receiver:
          variable expression [recurFunc]:
            type:
              lambda type [(i8)->i8]
        parameters:
          literal expression [233]:
            primary type [i8]
        type:
          primary type [i8]
```
