### ISSUE TITLE
AST should generated something like sourcemap

### ISSUE THREAD

**Issue by AkimotoAkari** [bC-Programming-Language-StandardCouncil/bC-Document#15]
便于debug啊还有toJS什么的

**Comment by ice1000** [comment]
`Cmc.Ast.Dump`

**Comment by ice1000** [comment]
```yaml
statement list:
  variable declaration [recurFunc]:
    type:
      lambda type [(i8)->i8]
    initialize expression:
      lambda:
        type:                                               
          lambda type [(i8)->i8]     
        parameters:                   
          variable declaration [a]:   
            type:                  
              primary type [i8]         
            initialize expression:  
              null expression           
        body:                             
          statement list:                     
            return statement:                                       
              function call expression:                    
                receiver:                  
                  variable expression [recur]:    
                    type:                   
                      lambda type [(i8)->i8]  
                parameters:                     
                  variable expression [a]:              
                    type:
                      primary type [i8] 
                type:
                  i8 
  variable declaration [gg]:    
    type:                               
      primary type [i8]             
    initialize expression:                   
      null expression                    
  assignment statemnt:        
    lhs:  
      variable expression [gg]:   
        type:                
          primary type [i8]   
    rhs:                      
      function call expression:      
        receiver:                     
          variable expression [recurFunc]:    
            type:            
              lambda type [(i8)->i8]     
        parameters:            
          literal expression [233]:   
            primary type [i8]         
        type:                  
          primary type [i8]  

  assignment statemnt:        
    lhs:  
      variable expression [gg]:   
        type:                
          primary type [i8]   
    rhs:                      
      function call expression:      
        receiver:                     
          variable expression [recurFunc]:    
            type:            
              lambda type [(i8)->i8]     
        parameters:            
          literal expression [233]:   
            primary type [i8]         
        type:                  
          primary type [i8]  
```
